routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "ProduitController@index");
Route::resource("produit", "ProduitController");
Route::resource("notice", "NoticeController");

app/Produit.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Produit extends Model
{
    protected $fillable = ['name', 'description', 'plateform', 'price', 'code'];

    public function notices() {
        return $this->hasMany(Notice::class);
    }

    public function achat() {
        return $this->belongsTo(Achat::class);
    }
}

app/Http/Controllers/ProduitController.php
<?php

namespace App\Http\Controllers;

use App\Produit;
use App\Notice;
use Illuminate\Http\Request;

class ProduitController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $produit = Produit::all();
        $search = $request->get('search');
        if ($search) {
            $produit = Produit::where('name', 'like', '%' . $search . '%')
            ->orWhere('description', 'like', '%' . $search . '%')
            ->orWhere('plateform', 'like', '%' . $search . '%')
            ->orWhere('price', 'like', '%' . $search . '%')
            ->get();
        } else {
          $produit = Produit::all();
        }

        return view('produit.index', ['produits' => $produit, 'search' => $search]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('produit.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $produit = new Produit;
        $produit->name = $request->input('name');
        $produit->description = $request->input('description');
        $produit->plateform = $request->input('plateform');
        $produit->price = $request->input('price');
        $produit->code = $request->input('code');
        $produit->save();

        return redirect()->action([ProduitController::class, 'index']);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function show(Produit $produit)
    {
        return view('produit.show', ['prod' => $produit]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function edit(Produit $produit)
    {
        return view('produit.edit', ['prod' => $produit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Produit $produit)
    {
        $prod = Produit::find($produit->id);
        $prod->update([
            'name' => $request->input('name'),
            'description' => $request->input('description'),
            'plateform' => $request->input('plateform'),
            'price' => $request->input('price'),
            'code' => $request->input('code'),
        ]);

        return redirect()->action([ProduitController::class, 'index']);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Produit  $produit
     * @return \Illuminate\Http\Response
     */
    public function destroy(Produit $produit)
    {
        $produit->notices()->delete();
        $produit->delete();
        return redirect()->action([ProduitController::class, 'index']);
    }
}

resources/views/produit/create.blade.php
@extends('produit.form')
@section('page-title')
    Add New Game
@endsection
@section('action')
    {{ route('produit.store') }}
@endsection

resources/views/produit/edit.blade.php
@extends('produit.form')
@section('page-title')
    Edit Game - {{ $prod->name }}
@endsection
@section('action'){{ route('produit.update', $prod) }}@endsection
@section('method') @method("PUT") @endsection
@section('name'){{ $prod->name }}@endsection
@section('description'){{ $prod->description }}@endsection
@section('plateform'){{ $prod->plateform }}@endsection
@section('price'){{ $prod->price }}@endsection
@section('code'){{ $prod->code }}@endsection

resources/views/produit/form.blade.php
@extends('application')
@section('page-title')
  @yield('page-title')
@endsection
@section('page-content')
  <div class="container mb-5 mt-3">
    <form method="post" action="@yield('action')">
      @yield('method')
      @csrf
        <div class="form-group">
          <label for="name">Game Name</label>
          <input type="text" class="form-control" id="name" name="name" value="@yield('name')">
        </div>
        <div class="form-group">
          <label for="description">Description</label>
          <input type="text" class="form-control" name="description" id="description" value="@yield("description")">
        </div>
        <div class="form-group">
          <label for="plateform">Plateform</label>
          <select class="form-control" name="plateform" id="plateform">
            <option>PC (Master Race)</option>
            <option>Xbox Series X</option>
            <option>Xbox ONE</option>
            <option>PS5</option>
            <option>PS4</option>
          </select>
        </div>
        <div class="form-group">
          <label for="price">Price</label>
          <input type="number" class="form-control" name="price" id="price" value="@yield("price")">
        </div>
        <div class="form-group">
          <label for="code">Code</label>
          <input type="text" class="form-control" name="code" id="code" value="@yield("code")">
        </div>
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
@endsection

resources/views/produit/index.blade.php
@extends('application')
@section('page-title')
    All Games
@endsection
@section('page-content')
    <div class="container">
        @if($search)
            <p class="mt-3">Search result for: {{ $search }}</p>
            <a href="{{route("produit.index")}}" class="mb-5">Return to list</a>
        @endif
    </div>
    <div class="container">

        <a class="btn btn-outline-success mt-3" href="{{ route("produit.create") }}">Add Game</a>

        <table class="table table-bordered mt-3">
            <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Plateform</th>
                <th scope="col">Price</th>
                <th scope="col">Note</th>
                <th scope="col">Go to...</th>
            </tr>
            </thead>
            <tbody>

            @foreach($produits as $prod)
                <tr>
                    <td>{{ $prod->name }}</td>
                    <td>{{ $prod->description }}</td>
                    <td>{{ $prod->plateform }}</td>
                    <td>{{ $prod->price }} €</td>
                    <td>
                        @foreach($prod->notices as $noti)
					        <li class="list-group" aria-current="true">{{ $noti->note }} /10</li>
                        @endforeach
                    </td>
                    <td class="d-flex" style="size: inherit">
                        <a class="btn btn-outline-success mr-2" href="{{ route("produit.show", $prod) }}">Check this game</a>
                        <a class="btn btn-outline-info mr-2" href="{{ route("produit.edit", $prod) }}">Edit</a>
                        <form action="{{ route("produit.destroy", $prod->id) }}" method="post">
                            <input class="btn btn-outline-danger" type="submit" value="Delete"/>
                            @method('delete')
                            @csrf
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
@endsection

resources/views/produit/show.blade.php
@extends('application')
@section('page-title')
  {{ $prod->name }}
@endsection

@section('page-content')
  <br>
  <div class="container">
    <div class="d-flex">
      <a class="btn btn-outline-primary mr-2" href="{{ route("produit.index") }}">Back</a>
    </div>
    <br>
    <div class="card">
      <div class="card-body">
        <h5 class="card-title">{{ $prod->name }} - @foreach($prod->notices as $noti){{ $noti->note }}@endforeach /10</h5>
        <h6 class="card-subtitle mb-2 text-muted">{{ $prod->price }} €</h6>
        <p class="card-text">
            <strong>Description: </strong>
            {{ $prod->description }}
        </p>
        <p class="card-text">
          <strong>Plateform: </strong>
        </p>
        <ul class="list-group list-group-flush mb-3">
          {{ $prod->plateform }}
        </ul>
        <p class="card-text">
          <strong>Notices: </strong>
        </p>
        <ul class="list-group list-group-flush mb-3">
            @foreach($prod->notices as $noti)
                <li class="list-group-item">
                    <a href="{{ route("notice.show", $noti) }}">{{ $noti->avis/*." ".$memb->firstname." ".$memb->lastname*/ }}</a>
                </li>
            @endforeach
        </ul>
        <div class="d-flex">
            <a class="btn btn-outline-primary mr-2" href="{{ route("notice.create", ["produit"=>$prod]) }}">Add Notice</a>
            <a class="btn btn-outline-info mr-2" href="{{ route("produit.edit", $prod) }}">Edit</a>
            <form action="{{ route("produit.destroy", $prod->id) }}" method="post">
              <input class="btn btn-outline-danger" type="submit" value="Delete"/>
              @method('delete')
              @csrf
            </form>
        </div>
      </div>
    </div>
  </div>
@endsection