routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', "ProduitController@index");
Route::resource("produit", "ProduitController");
Route::resource("notice", "NoticeController");

app/Notice.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Notice extends Model
{
    protected $fillable = ['avis', 'note'];

    public function produit() {
        return $this->belongsTo(Produit::class);
    }

    public function user() {
        return $this->belongsTo(User::class);
    }
}

app/Http/Controllers/NoticeController.php
<?php

namespace App\Http\Controllers;

use App\Notice;
use App\Produit;
use Illuminate\Http\Request;

class NoticeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $notice = Notice::all();
        $search = $request->get('search');
        if ($search) {
            $notice = Notice::where('avis', 'like', '%' . $search . '%')
            ->orWhere('note', 'like', '%' . $search . '%')
            ->get();
        } else {
            $notice = Notice::all();
        }

        return view('notice.index', ['notice' => $notice, 'search' => $search]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request, Produit $produit)
    {
        $produit_id = $request->input('produit');

        $id = $request->input('id');
        return view('notice.createnotice', ['id' => $id, 'produit' => Produit::find($produit_id)]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $notice = new Notice;
        $notice->avis = $request->input('avis');
        $notice->note = $request->input('note');
        $notice->produit_id = $request->input('produit_id');
        $notice->save();

        $produit = Produit::find($request->input('produit_id'));
        return redirect()->route('produit.show', ['produit' => $produit]);
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function show(Notice $notice)
    {
        return view('notice.show', ['notice' => $notice]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function edit(Notice $notice)
    {
        $produit = Produit::all();
        return view('notice.edit', ['notice' => $notice, 'produit' => $produit]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Notice $notice)
    {
        $avis = $request->input('avis');
        $note = $request->input('note');
        $produit_id = $request->input('produit');

        $notice = Notice::find($notice->id);
        $notice->avis = $avis;
        $notice->note = $note;
        $notice->produit_id = $produit_id;
        $notice->push();
        return redirect()->route('notice.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Notice  $notice
     * @return \Illuminate\Http\Response
     */
    public function destroy(Notice $notice)
    {
        $notice->delete();
        return redirect()->route('notice.index');
    }
}

resources/views/notice/create.blade.php
@extends("notice.form")
@section("page-title")
	Add Notice
@endsection
@section("action")
	{{ route("notice.store") }}
@endsection
@section('produit')
	{{ $produit->name."  ".$produit->plateform }}
@endsection
@section('produit_id')
	{{ $produit->id }}
@endsection

resources/views/notice/createnotice.blade.php
@extends("notice.formnotice")
@section("page-title")
	Add Notice
@endsection
@section("action")
	{{ route("notice.store") }}
@endsection
@section('produit')
	{{ $produit->name."  ".$produit->plateform }}
@endsection
@section('produit_id')
	{{ $produit->id }}
@endsection

resources/views/notice/edit.blade.php
@extends("notice.form")
@section("page-title")
    Edit Notice
@endsection
@section("action"){{ route("notice.update", $notice) }}@endsection
@section("method") @method("PUT") @endsection
@section("avis"){{ $notice->avis }}@endsection
@section("note"){{ $notice->note }}@endsection
@section('produit')
    <select name="produit" class="form-control">
        @foreach ($produit as $prod)
            <option value="{{ $prod->id }}">{{ $prod->name." ".$notice->note }}</option>
        @endforeach
    </select>
@endsection

resources/views/notice/form.blade.php
@extends('application')
@section('page-title')
    @yield('page-title')
@endsection
@section('page-content')
    <div class="container mb-5 mt-3">
        <form method="post" action="@yield('action')">
            @csrf
            @method("put")
            <div class="form-row">
                <div class="col">
                    <label for="avis">Notice</label>
                    <input type="text" class="form-control" name="avis" id="avis" value="@yield("avis")">
                </div>
                <div class="form-group">
                    <label for="note">Note</label>
                    <select class="form-control" name="note" id="note">
                      <option>0</option>
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                      <option>4</option>
                      <option>5</option>
                      <option>6</option>
                      <option>7</option>
                      <option>8</option>
                      <option>9</option>
                      <option>10</option>
                    </select>
                </div>
            </div>
            <label for="produit">Product</label>
            <fieldset>
                <div class="form-row mb-5">
                  <div class="col">
                    @yield("produit")
                  </div>
                </div>
            </fieldset>
            <input type="hidden" name="produit_id" value="@yield("produit_id")">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/notice/formnotice.blade.php
@extends('application')
@section('page-title')
    @yield('page-title')
@endsection
@section('page-content')
    <div class="container mb-5 mt-3">
        <form method="post" action="@yield('action')">
            @csrf
            <div class="form-row">
                <div class="col">
                    <label for="avis">Notice</label>
                    <input type="text" class="form-control" name="avis" id="avis" value="@yield("avis")">
                </div>
                <div class="form-group">
                    <label for="note">Note</label>
                    <select class="form-control" name="note" id="note">
                      <option>0</option>
                      <option>1</option>
                      <option>2</option>
                      <option>3</option>
                      <option>4</option>
                      <option>5</option>
                      <option>6</option>
                      <option>7</option>
                      <option>8</option>
                      <option>9</option>
                      <option>10</option>
                    </select>
                </div>
            </div>
            <label for="produit">Product</label>
            <fieldset>
                <div class="form-row mb-5">
                  <div class="col">
                    @yield("produit")
                  </div>
                </div>
            </fieldset>
            <input type="hidden" name="produit_id" value="@yield("produit_id")">
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/notice/index.blade.php
@extends('application')
@section('page-title')
    All Notices
@endsection
@section('page-content')
    <div class="container">
        @if($search)
            <p class="mt-3">Search result for: {{ $search }}</p>
            <a href="{{route("notice.index")}}" class="mb-5">Return to list</a>
        @endif
    </div>
    <div class="container">

        <table class="table table-bordered mt-3">
            <thead>
            <tr>
                <th scope="col">Avis</th>
                <th scope="col">Note</th>
                <th scope="col">Notice for...</th>
                <th scope="col">Options</th>
            </tr>
            </thead>
            <tbody>

            @foreach($notice as $noti)
                <tr>
                    <td>{{ $noti->avis }}</td>
                    <td>{{ $noti->note }} /10</td>
                    <td>{{ $noti->produit->name}}</td>
                    <td class="d-flex" style="size: inherit">
                        <a class="btn btn-outline-success mr-2" href="{{ route("notice.show", $noti) }}">Show</a>
                        <a class="btn btn-outline-info mr-2" href="{{ route("notice.edit", $noti) }}">Edit</a>
                        <form action="{{ route("notice.destroy", $noti->id) }}" method="post">
                            <input class="btn btn-outline-danger" type="submit" value="Delete"/>
                            @method('delete')
                            @csrf
                        </form>
                    </td>
                </tr>
            @endforeach

            </tbody>
        </table>
    </div>
@endsection

resources/views/notice/show.blade.php
@extends('application')
@section('page-title')
    Notice for {{ $notice->produit->name }}
@endsection

@section('page-content')
    <div class="container">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">{{--{{ $notice->member->lastname }} {{ $notice->member->firstname }}--}}</h5>
                <p class="card-text">
                    <strong>Note: </strong>
                </p>
                <h6 class="card-subtitle mb-2 text-muted">{{ $notice->note }} /10</h6>
                <p class="card-text">
                    <strong>Notice: </strong>
                    {{ $notice->avis }}
                </p>
                <div class="d-flex">
                    <a class="btn btn-outline-info mr-2" href="{{ route("notice.edit", $notice) }}">Edit Notice</a>
                    <form action="{{ route("notice.destroy", $notice->id) }}" method="post">
                        <input class="btn btn-outline-danger" type="submit" value="Delete"/>
                        @method('delete')
                        @csrf
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection